feature engineering
CertifaiAI/machine-learning-fundamentals pull request #41
Opened 2021-09-24 00:29 UTC by NazurahK0501

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New Exercise
- [x] Bug fix (Non-breaking change which fixes an issue)
- [ ] New feature (Non-breaking change which adds functionality)
- [ ] Breaking change (Fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Adding GitHub Action capabilities

# Tested on?

- [x] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

2021-09-27 02:03 UTC, OoiXinPeng approved these changes

2021-10-05 05:39 UTC, annabelle1217 commented on day_1/1S_Feature_Engineering.ipynb
> +    "Perform one-hot-encoding by using `get_dummies`. The first category of our data will be remove by using the **drop_first=True** because it contain the same information. It will be remove to prev
The `drop_first=True` explanation and "same information" here seems less clear to me
Suggested explanation:
Perform one-hot encoding by using `pd.get_dummies`. It converts categorical variable into dummy/indicator variables for each category. 

The column for the first category of our data will be removed by using the `drop_first=True` because it will contain the same information as the new column of the second category or for multiple categories, its information will be captured in the rest of the columns. It will be removed to prevent data redundancy in out dataset.

2021-10-06 03:56 UTC, annabelle1217 commented on day_1/1S_Feature_Engineering.ipynb
> +    "Best practice by mapping them into a new numeric value. "
means the method that use dictionary is the best practice? Sorry can't get the clear meaning here

2021-10-06 04:38 UTC, NazurahK0501 commented on day_1/1S_Feature_Engineering.ipynb
> +    "Perform one-hot-encoding by using `get_dummies`. The first category of our data will be remove by using the **drop_first=True** because it contain the same information. It will be remove to prev
alright, will update it accordingly

2021-10-06 07:25 UTC, annabelle1217 requested changes
You can rename the "1S_Feature_Engineering" to "3S_Feature Engineering" 
without the underscore in between feature engineering following naming of other notebooks
I will rename feature selection start with 4S_

2021-10-06 08:22 UTC, annabelle1217 commented on day_1/3E_Feature_Engineering.ipynb
> +    "from scipy.stats.mstats import winsorize"
Forgot about this haha
Do you want to put the import to the top?

2021-10-06 08:23 UTC, NazurahK0501 commented on day_1/3E_Feature_Engineering.ipynb
> +    "from scipy.stats.mstats import winsorize"
hmm, i think it is better to put it on the top

2021-10-06 09:03 UTC, annabelle1217 approved these changes
All good to merge

2021-10-06 09:50 UTC, merged